name: Deploy minikube and Kind
on: [push, pull_request]

env:
  OUTPUT_LOG_FILENAME: output.log

jobs:
  deploy:
    strategy:
      matrix:
        environment: ['minikube', 'kind']
    runs-on: ubuntu-latest
    name: deploy to ${{ matrix.environment }}
    steps:
    - name: Start ${{ matrix.environment }}
      uses: ${{ (matrix.environment == 'minikube' && 'medyagh/setup-minikube@master') || (matrix.environment == 'kind' && 'engineerd/setup-kind@v0.5.0') }}
      with:
        ${{ (matrix.environment == 'kind' && 'version') || '' }}: "v0.17.0"
    - name: checkinfo
      run: |
       echo -e "Nods:\n$(kubectl get pods -A)" >> ${{ env.OUTPUT_LOG_FILENAME }}
       echo -e "${{ matrix.environment }} version:\n$(kubectl version --short)" >> ${{ env.OUTPUT_LOG_FILENAME }}
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
          path: ${{ env.OUTPUT_LOG_FILENAME }}