name: Test Clusters

on: push

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup KinD
      uses: engineerd/setup-kind@v0.6.0
      with:
        version: v1.19.7
        nodes: 3
      run: |
        kind create cluster --config=./kind-config.yaml

    - name: Check KinD
      run: |
        kubectl get nodes

  minikube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Minikube
      uses: hashicorp/setup-minikube@v1.0.0
      with:
        kubernetes_version: v1.19.7
        memory: 4g
        nodes: 3
      run: |
        minikube start

    - name: Check Minikube
      run: |
        kubectl get nodes