name: Deploy-Kubernetes-Clusters

on: push

jobs:
  kind-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install KinD
      run: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.10.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Spin up KinD cluster
      run: kind create cluster --name kind-test --config 9ks.yaml

    - name: Get cluster info
      run: kubectl cluster-info --context kind-kind-test

    - name: Display nodes
      run: kubectl get nodes

    - name: Delete cluster
      run: kind delete cluster --name kind-test

  minikube-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/

    - name: Start Minikube
      run: minikube start

    - name: Get cluster info
      run: kubectl cluster-info

    - name: Display nodes
      run: kubectl get nodes

    - name: Stop Minikube
      run: minikube stop