name: Deploy minikube and Kind
on:
  - push
concurrency: deploy   # This will run the jobs concurrently
jobs:
  deploy_minikube:
    runs-on: ubuntu-latest
    name: deploy to minikube
    steps:
    - name: Start minikube
      uses: medyagh/setup-minikube@master    # Switch to latest release instead of master
    - name: checkinfo
      run: |
       echo -e "Nods:\n$(kubectl get pods -A)" >> output_minikube.log
       echo -e "Minikube version:\n$(kubectl version --short)" >> output_minikube.log
    - name: Upload report
      uses: actions/upload-artifact@v2   # Use v2 as v3 is not available
      with:
          path: output_minikube.log

  deploy_KinD:
    runs-on: ubuntu-latest
    name: deploy to KinD
    steps:
    - name: Start KinD
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.17.0"
    - name: checkinfo
      run: |
       echo -e "Nods:\n$(kubectl get pods -A)" >> output_kind.log
       echo -e "KinD version:\n$(kubectl version --short)" >> output_kind.log
    - name: Upload report
      uses: actions/upload-artifact@v2   # Use v2 as v3 is not available
      with:
          path: output_kind.log